plugins {
    id 'org.springframework.boot' version '3.3.5'
    id 'java'
}

group = 'com.elastic'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Gradle 9'a Spring Boot'un tüm kütüphane versiyon haritasını (BOM) açıkça dikte ediyoruz:
    implementation platform('org.springframework.boot:spring-boot-dependencies:3.3.5')

    // Web ve Elasticsearch bağımlılıkları
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'

    // Source: https://mvnrepository.com/artifact/org.projectlombok/lombok
    implementation("org.projectlombok:lombok:1.18.42")
    // Doğrudan versiyon belirterek indirme (Sürüm belirsizliği hatasını çözer)
    implementation 'org.elasticsearch.client:elasticsearch-rest-client:8.11.1'

    // Apache Core 5 kütüphanesi (Versiyonu ile birlikte)
    implementation 'org.apache.httpcomponents.core5:httpcore5:5.2.4'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

