spring:
  elasticsearch:
    uris: http://localhost:9200
    rest:
      headers:
        Accept: "application/vnd.elasticsearch+json;compatible-with=8"
        Content-Type: "application/vnd.elasticsearch+json;compatible-with=8"
xpack:
  security:
    enabled: false
  http:
    ssl:
      enabled: false
